version: '3.8'

services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: QAZwsx@123
      MYSQL_DATABASE: doctor_patient
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  doctor_patient_app:
    build: .
    container_name: doctor_patient_app
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/doctor_patient?createTableIfNotExists=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: QAZwsx@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_APPLICATION_NAME: doctor_patient_project
      SERVER_PORT: 8082
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:


